server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nxtgen_inventory?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: BlasDeGuzmanRelova123@

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false